### ISSUE TITLE
typo in function filterfunc in filter.py?

### ISSUE THREAD

**Issue by nanakosh** [foxfixfax/PyCCE#8]
Hello! This is my first time using GitHub, please excuse me if this is not the appropriate place to comment.

I have noticed that the first lines of `filterfunc` in `filter.py`,

` fs = np.empty(ts.shape)`
` ks = np.empty(npulses) * 2`
 `ks[:npulses] = np.arange(npulses)`
 `ks[npulses:] = np.arange(npulses)`

causes `gaussian_phase` to break for pulse number N=2, because of mismatch in array shapes. It looks like modifying

`ks = np.empty(npulses) * 2`

to

`ks = np.empty(npulses * 2)`

seems to solve this, and also seems to make more sense.

**Comment by foxfixfax** [comment]
It does look like a typo! It was already corrected in the dev version (will be online within a couple of days) to the following:
`ks = np.r_[np.arange(npulses), np.arange(npulses)]`
Thank you for noticing!
